AddressBook/Models/AddressViewModel.cs
using AddressBook.DtoModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AddressBook.Models
{
    public class AddressViewModel
    {
        public int Id { get; set; }
        public Address Address { get; set; }
        public string AddressName { get; set; }
        public string City { get; set; }
        public IEnumerable<Contact> Contacts { get; set; }
    }
}

AddressBook/Models/ContactViewModel.cs
using AddressBook.DtoModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AddressBook.Models
{
    public class ContactViewModel
    {    
        public int Id { get; set; }
        public Contact Contact { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int PhoneNo { get; set; }        
        public IEnumerable<Address> Addresses { get; set; }
    }
}

AddressBook/Models/ErrorViewModel.cs
using System;

namespace AddressBook.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AddressBook/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AddressBook.DataLayer;
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;

namespace AddressBook.Controllers
{
    public class AddressController : Controller
    {
        private IAddressRepository _addressRepository;
        private IContactRepository _contactRepository;
        public AddressController(IAddressRepository addressRepository, IContactRepository contactRepository)
        {
            _addressRepository = addressRepository;
            _contactRepository = contactRepository;
        }

        public ActionResult Index()
        {
            var adresses = from address in _addressRepository.GetAllWithContact()
                             select address;
            return View(adresses);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(AddressViewModel addressViewModel)
        {
            _addressRepository.Create(addressViewModel.Address);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var addressVM = new AddressViewModel()
            {
                Address = _addressRepository.GetById(id),

            };
            return View(addressVM);
        }

        [HttpPost]
        public IActionResult Update(AddressViewModel addressViewModel)
        {
            if (!ModelState.IsValid)
            {
                addressViewModel.Contacts = _contactRepository.GetAll();
                return View(addressViewModel);
            }
            _addressRepository.Update(addressViewModel.Address);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var address = _addressRepository.GetById(id);
            return View(address);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = _addressRepository.GetById(id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(AddressViewModel addressViewModel)
        {
            if (ModelState.IsValid)
            {
                var address = _addressRepository.GetById(addressViewModel.Id);
                _addressRepository.Delete(address);
                return RedirectToAction("index");
            }
            return View();
        }
    }
}

AddressBook/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AddressBook.DataLayer;
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AddressBook.Controllers
{
    public class ContactController : Controller
    {
        private IAddressRepository _addressRepository;
        private IContactRepository _contactRepository;
        public ContactController(IAddressRepository addressRepository, IContactRepository contactRepository)
        {
            _addressRepository = addressRepository;
            _contactRepository = contactRepository;
        }

        public ActionResult Index(string SearchString)
        {
            var contacts = from contact in _contactRepository.GetAllWithAddress()
                           select contact;

            if (!String.IsNullOrEmpty(SearchString))
            {
                contacts = contacts.Where(s => s.Address.AddressName.Contains(SearchString)).ToList();
            }
            return View(contacts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var contactVM = new ContactViewModel()
            {
                Addresses = _addressRepository.GetAll()
            };
            return View(contactVM);
        }

        [HttpPost]
        public IActionResult Create(ContactViewModel contactViewModel)
        {
            if (!ModelState.IsValid)
            {
                contactViewModel.Addresses = _addressRepository.GetAll();
                return View(contactViewModel);
            }
            _contactRepository.Create(contactViewModel.Contact);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var contactVM = new ContactViewModel()
            {
                Contact = _contactRepository.GetById(id),
                Addresses = _addressRepository.GetAll()
            };
            return View(contactVM);
        }

        [HttpPost]
        public IActionResult Update(ContactViewModel contactViewModel)
        {
            if (!ModelState.IsValid)
            {
                contactViewModel.Addresses = _addressRepository.GetAll();
                return View(contactViewModel);
            }
            _contactRepository.Update(contactViewModel.Contact);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var contact = _contactRepository.GetById(id);
            return View(contact);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var model = _contactRepository.GetById(id);

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(ContactViewModel contactViewModel)
        {
            if (ModelState.IsValid)
            {
                var contact = _contactRepository.GetById(contactViewModel.Id);
                _contactRepository.Delete(contact);
                return RedirectToAction("index");
            }
            return View();
        }
    }
}

AddressBook/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AddressBook.Models;

namespace AddressBook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AddressBook/Views/Address/Create.cshtml
@model AddressViewModel;
@{
    ViewData["Title"] = "Create";
}
    <div class="row orderForm">
        <div class="col-md-6">
            <form asp-controller="Address" asp-action="Create" method="post" class="form-horizontal" role="form">
                <h3 class="col-md-offset-2">Create new address</h3>
                <div class="form-group">
                    <label asp-for="Address.AddressName" class="col-md-2 control-label"></label>
                    <div class="col-md-6">
                        <input asp-for="Address.AddressName" class="form-control" placeholder="Enter address name" />
                        <span asp-validation-for="Address.AddressName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Address.City" class="col-md-2 control-label"></label>
                    <div class="col-md-6">
                        <input asp-for="Address.City" class="form-control" placeholder="Enter city" />
                        <span asp-validation-for="Address.City" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="btn-group col-md-offset-2 col-md-6">
                        <input class="btn btn-info" type="submit" value="Return" asp-controller="Address" asp-action="Index" />
                        <input class="btn btn-success" type="submit" value="Create" />
                    </div>
                </div>
            </form>
        </div>
    </div>

AddressBook/Views/Address/Delete.cshtml
@model AddressBook.DtoModel.Address;
@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Address</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AddressName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AddressName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-info" asp-action="Index">Back to List</a>
    </form>
</div>

AddressBook/Views/Address/Details.cshtml
@model AddressBook.DtoModel.Address;
@{
    ViewData["Title"] = "Details";
}

    <div>
        <h4>Address details</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.AddressName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AddressName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.City)
            </dd>
        </dl>
    </div>

AddressBook/Views/Address/Index.cshtml
@model IEnumerable<AddressBook.DtoModel.Address>
@{
    ViewData["Title"] = "Index";
}

<a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Address" asp-action="Create">Create new address</a>

<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th>AddressName</th>
            <th>City</th>
            <th>Edit</th>
            <th>Details</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var address in Model)
        {
            <tr>
                <td>@address.AddressName</td>
                <td>@address.City</td>
                <td><a class="btn btn-info" asp-area="" asp-controller="Address" asp-action="Update" asp-route-id="@address.Id">Edit</a></td>
                <td><a class="btn btn-info" asp-area="" asp-controller="Address" asp-action="Details" asp-route-id="@address.Id">Details</a></td>
                <td><a class="btn btn-danger" asp-area="" asp-controller="Address" asp-action="Delete" asp-route-id="@address.Id">Delete</a></td>
            </tr>
        }
    </tbody>
</table>

AddressBook/Views/Address/Update.cshtml
@model AddressViewModel;
@{
    ViewData["Title"] = "Update";
}

    <div class="row orderForm">
        <div class="col-md-6">
            <form asp-controller="Address" asp-action="Update" method="post" class="form-horizontal" role="form">
                <h3 class="col-md-offset-2">Update address</h3>
                @Html.HiddenFor(m => Model.Address.Id)
                <div class="form-group">
                    <label asp-for="Address.AddressName" class="col-md-2 control-label"></label>
                    <div class="col-md-6">
                        <input asp-for="Address.AddressName" class="form-control" placeholder="Enter address name" />
                        <span asp-validation-for="Address.AddressName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Address.City" class="col-md-2 control-label"></label>
                    <div class="col-md-6">
                        <input asp-for="Address.City" class="form-control" placeholder="Enter city" />
                        <span asp-validation-for="Address.City" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="btn-group col-md-offset-2 col-md-6">
                        <input class="btn btn-info" type="submit" value="Return" asp-controller="Address" asp-action="Index" />
                        <input class="btn btn-success" type="submit" value="Update" />
                    </div>
                </div>
            </form>
        </div>
    </div>

AddressBook/Views/Contact/Create.cshtml
@model ContactViewModel
@{
    ViewData["Title"] = "Create";
}

    <div class="row orderForm">
        <div class="col-md-6">
            <form asp-controller="Contact" asp-action="Create" method="post" class="form-horizontal" role="form">
                <h3 class="col-md-offset-2">Create new contact</h3>
                <div class="form-group">
                    <label asp-for="Contact.Address" class="col-md-2 control-label"></label>
                    <div class="col-md-4">
                        @Html.DropDownListFor(m => m.Contact.AddressId,
                                               new SelectList(Model.Addresses.Select(x => new { Value = x.Id, Text = x.AddressName }), "Value", "Text"), "Select address",
                                               htmlAttributes: new { @class = "form-control border-input" })
                        <span asp-validation-for="Contact.Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Contact.FirstName" class="col-md-2 control-label">FirstName</label>
                    <div class="col-md-6">
                        <input asp-for="Contact.FirstName" class="form-control" placeholder="Enter first name" />
                        <span asp-validation-for="Contact.FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Contact.LastName" class="col-md-2 control-label">LastName</label>
                    <div class="col-md-6">
                        <input asp-for="Contact.LastName" class="form-control" placeholder="Enter last name" />
                        <span asp-validation-for="Contact.LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Contact.PhoneNo" class="col-md-2 control-label">PhoneNumber</label>
                    <div class="col-md-6">
                        <input asp-for="Contact.PhoneNo" class="form-control" placeholder="Enter phone number" />
                        <span asp-validation-for="Contact.PhoneNo" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="btn-group col-md-offset-2 col-md-6">
                        <input class="btn btn-info" type="submit" value="Return" asp-controller="Contact" asp-action="Index" />
                        <input class="btn btn-success" type="submit" value="Create" />
                    </div>
                </div>
            </form>
        </div>
    </div>

AddressBook/Views/Contact/Delete.cshtml
@model AddressBook.DtoModel.Contact
@{
    ViewData["Title"] = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address.AddressName)
        </dd>
    </dl>
    
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-info" asp-action="Index">Back to List</a>
        </form>
    </div>

AddressBook/Views/Contact/Details.cshtml
@model AddressBook.DtoModel.Contact;
@{
    ViewData["Title"] = "Details";
}

    <div>
        <h4>Contact details</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.PhoneNo)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PhoneNo)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Address.AddressName)
            </dd>
        </dl>
    </div>

AddressBook/Views/Contact/Index.cshtml
@model IEnumerable<AddressBook.DtoModel.Contact>
@{
    ViewData["Title"] = "Index";
}

@using (Html.BeginForm())
{
    <p>
        Search contact by address: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}  
    <a class="btn btn-success mt-5" style="margin: 10px" asp-controller="Contact" asp-action="Create">Create new contact</a>
    <table class="table table-striped table-hover ">
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>Edit</th>
                <th>Details</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var contact in Model)
            {
                <tr>
                    <td>@contact.FirstName</td>
                    <td>@contact.LastName</td>
                    <td>@contact.Address.AddressName</td>
                    <td><a class="btn btn-info" asp-area="" asp-controller="Contact" asp-action="Update" asp-route-id="@contact.Id">Edit</a></td>
                    <td><a class="btn btn-info" asp-area="" asp-controller="Contact" asp-action="Details" asp-route-id="@contact.Id">Details</a></td>
                    <td><a class="btn btn-danger" asp-area="" asp-controller="Contact" asp-action="Delete" asp-route-id="@contact.Id">Delete</a></td>
                </tr>
            }
        </tbody>
    </table>

AddressBook/Views/Contact/Update.cshtml
@model ContactViewModel

@{
    ViewData["Title"] = "Update";
}

    <div class="row orderForm">
        <div class="col-md-6">
            <form asp-controller="Contact" asp-action="Update" method="post" class="form-horizontal" role="form">
                <h3 class="col-md-offset-2">Update contact</h3>
                @Html.HiddenFor(m => Model.Contact.Id)

                <div class="form-group">
                    <label asp-for="Contact.Address" class="col-md-2 control-label"></label>
                    <div class="col-md-6">

                        @Html.DropDownListFor(m => m.Contact.AddressId,
                                                          new SelectList(Model.Addresses.Select(x => new { Value = x.Id, Text = x.AddressName }), "Value", "Text"),
                                                          htmlAttributes: new { @class = "form-control border-input" })
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Contact.FirstName" class="col-md-2 control-label"></label>
                    <div class="col-md-6">
                        <input asp-for="Contact.FirstName" class="form-control" placeholder="Enter first name" />
                        <span asp-validation-for="Contact.FirstName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Contact.LastName" class="col-md-2 control-label"></label>
                    <div class="col-md-6">
                        <input asp-for="Contact.LastName" class="form-control" placeholder="Enter last name" />
                        <span asp-validation-for="Contact.LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Contact.PhoneNo" class="col-md-2 control-label"></label>
                    <div class="col-md-6">
                        <input asp-for="Contact.PhoneNo" class="form-control" placeholder="Enter phone number" />
                        <span asp-validation-for="Contact.PhoneNo" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="btn-group col-md-offset-2 col-md-6">
                        <input class="btn btn-info" type="submit" value="Return" asp-controller="Contact" asp-action="Index" />
                        <input class="btn btn-success" type="submit" value="Update" />
                    </div>
                </div>
            </form>
        </div>
    </div>

AddressBook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AddressBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddressBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AddressBook</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contacts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Address" asp-action="Index">Addresses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AddressBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>